version: '3'
services:

  #mailhog:
  #  image: mailhog/mailhog
  #  ports:
  #    - 8025:8025
  #   - 1025:1025
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: app
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./docker/app/php-settings.ini:/usr/local/etc/php/conf.d/php-settings.ini

    working_dir: /var/www
  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

  database:
    image: postgres:alpine
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_DATABASE:-laravel}
    restart: unless-stopped

  #database_testing:
  #    image: postgres:alpine
  #    ports:
  #        - '${FORWARD_DB_TEST_PORT:-5433}:5432'
  #    environment:
  #        POSTGRES_USER: ${DB_TESTING_USERNAME:-root}
  #        POSTGRES_PASSWORD: ${DB_TESTING_PASSWORD:-password}
  #        POSTGRES_DB: ${DB_TESTING_DATABASE:-laravel}
  #    restart: unless-stopped

volumes:
  db_data:

